#!/usr/bin/env bash
# Print the VPS's nginx sites: the backend's host proxied to its port, and each
# web app's static build on its own host. A host is served over HTTPS once its
# Let's Encrypt certificate exists, and over plain HTTP until then, so nginx never
# refers to a certificate it does not have. deploy/deploy.sh installs the result.
#
# Usage: nginx-sites.sh API_HOST API_PORT HOST=WEB_DIR...

set -euo pipefail

(($# >= 2)) || {
	echo "Usage: $0 API_HOST API_PORT HOST=WEB_DIR..." >&2
	exit 2
}

API_HOST=$1 API_PORT=$2
shift 2
LIVE=${LETSENCRYPT_LIVE:-/etc/letsencrypt/live}
ACME_ROOT=${ACME_ROOT:-/var/www/html}

has_cert() { [[ -f $LIVE/$1/fullchain.pem && -f $LIVE/$1/privkey.pem ]]; }

# The start of HOST's server block that serves it (HTTPS, or HTTP for now); with
# HTTPS, a plain HTTP block that redirects to it comes first.
server_start() {
	local host=$1
	if has_cert "$host"; then
		cat <<EOF
server {
    listen 80;
    listen [::]:80;
    server_name $host;

    location /.well-known/acme-challenge/ { root $ACME_ROOT; }
    location / { return 301 https://\$host\$request_uri; }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name $host;

    ssl_certificate $LIVE/$host/fullchain.pem;
    ssl_certificate_key $LIVE/$host/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
EOF
	else
		cat <<EOF
# No certificate yet: deploy/deploy.sh gets one when this host's DNS points here.
server {
    listen 80;
    listen [::]:80;
    server_name $host;

    location /.well-known/acme-challenge/ { root $ACME_ROOT; }
EOF
	fi
}

# The proxy settings for the backend, with how long a response may take.
proxy_to_backend() {
	cat <<EOF
        proxy_pass http://127.0.0.1:$API_PORT;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection \$vanguard_connection_upgrade;
        proxy_read_timeout $1;
        proxy_send_timeout $1;
EOF
}

cat <<'EOF'
# DLAS on this server: generated by deploy/nginx-sites.sh (run deploy/deploy.sh
# to regenerate it; edits made here are lost).

# "upgrade" only when the client asks for a WebSocket (Twilio's media stream).
map $http_upgrade $vanguard_connection_upgrade {
    default upgrade;
    ''      close;
}

EOF

printf '# The backend: its API, and the phone lines Twilio calls.\n'
server_start "$API_HOST"
cat <<EOF

    # Documents are up to 10 MB (server/app/services/uploads.py).
    client_max_body_size 12m;

    location / {
        # An agent's model may take up to a minute to answer.
$(proxy_to_backend 120s)
    }

    # A call's media stream stays open for as long as the call.
    location /telephony/media {
$(proxy_to_backend 1h)
    }
}
EOF

for site in "$@"; do
	host=${site%%=*} dir=${site#*=}
	printf '\n# %s\n' "$(basename "$dir")"
	server_start "$host"
	cat <<EOF

    root $dir;
    index index.html;

    # Vite names these after their content, so a new build never reuses a name.
    location /assets/ {
        expires 1y;
        add_header Cache-Control "public, immutable";
        try_files \$uri =404;
    }

    # The legal aid app's install manifest.
    location = /manifest.webmanifest {
        types { }
        default_type application/manifest+json;
        add_header Cache-Control "no-cache";
    }

    # Everything else (index.html, a service worker) is checked on every visit, so
    # a new build shows at once.
    location / {
        add_header Cache-Control "no-cache";
        try_files \$uri \$uri/ /index.html;
    }
}
EOF
done
