"""Uploaded files, AI-generated checklists, and T11 signatures on generated documents."""

from datetime import datetime
from enum import StrEnum

from sqlalchemy import JSON, Boolean, DateTime, ForeignKey, Integer, String, Text, UniqueConstraint
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database import Base, utcnow


class DocumentKind(StrEnum):
    NID_COPY = "nid_copy"
    MEDICAL_CERTIFICATE = "medical_certificate"
    GD_FIR_COPY = "gd_fir_copy"
    MARRIAGE_CERTIFICATE = "marriage_certificate"  # kabinnama
    BIRTH_CERTIFICATE = "birth_certificate"
    LAND_RECORD = "land_record"  # khatian / porcha / deed
    EMPLOYMENT_PROOF = "employment_proof"
    SCREENSHOT = "screenshot"
    PHOTO_EVIDENCE = "photo_evidence"
    INCOME_PROOF = "income_proof"
    SETTLEMENT_DRAFT = "settlement_draft"
    OTHER = "other"


class DocumentStatus(StrEnum):
    UPLOADED = "uploaded"
    PROCESSED = "processed"
    NEEDS_REVIEW = "needs_review"
    # Settlement drafts: approved by the officer and open for signature.
    APPROVED = "approved"
    # All required signers have signed.
    EXECUTED = "executed"


class Document(Base):
    __tablename__ = "documents"

    id: Mapped[int] = mapped_column(primary_key=True)
    case_id: Mapped[int] = mapped_column(ForeignKey("cases.id", ondelete="CASCADE"), index=True)
    kind: Mapped[DocumentKind] = mapped_column(String(30), default=DocumentKind.OTHER)
    status: Mapped[DocumentStatus] = mapped_column(String(20), default=DocumentStatus.UPLOADED)

    filename: Mapped[str | None] = mapped_column(String(255))
    content_type: Mapped[str | None] = mapped_column(String(100))
    storage_path: Mapped[str | None] = mapped_column(String(500))
    size_bytes: Mapped[int | None] = mapped_column(Integer)
    # SHA-256 of the uploaded bytes, or of `content` for generated documents.
    sha256: Mapped[str | None] = mapped_column(String(64), index=True)

    # Generated documents (settlement drafts) keep their text here.
    content: Mapped[str | None] = mapped_column(Text)
    # T6 output: OCR text and a short plain-language summary.
    extracted_text: Mapped[str | None] = mapped_column(Text)
    summary: Mapped[str | None] = mapped_column(Text)
    # Party IDs who must sign before the document is executed (T11).
    required_signers: Mapped[list[int]] = mapped_column(JSON, default=list)

    uploaded_by: Mapped[str | None] = mapped_column(String(64))
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utcnow)
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=utcnow, onupdate=utcnow
    )

    signatures: Mapped[list["Signature"]] = relationship(
        back_populates="document", cascade="all, delete-orphan", lazy="selectin"
    )


class ChecklistStatus(StrEnum):
    MISSING = "missing"
    PROVIDED = "provided"
    WAIVED = "waived"


class ChecklistItem(Base):
    """A document the case needs, as generated by the T6 agent."""

    __tablename__ = "checklist_items"
    __table_args__ = (UniqueConstraint("case_id", "item_key"),)

    id: Mapped[int] = mapped_column(primary_key=True)
    case_id: Mapped[int] = mapped_column(ForeignKey("cases.id", ondelete="CASCADE"), index=True)
    item_key: Mapped[str] = mapped_column(String(40))
    label: Mapped[str] = mapped_column(String(200))
    label_bn: Mapped[str | None] = mapped_column(String(200))
    required: Mapped[bool] = mapped_column(Boolean, default=True)
    status: Mapped[ChecklistStatus] = mapped_column(String(20), default=ChecklistStatus.MISSING)
    document_id: Mapped[int | None] = mapped_column(ForeignKey("documents.id", ondelete="SET NULL"))
    note: Mapped[str | None] = mapped_column(Text)
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=utcnow, onupdate=utcnow
    )


class Signature(Base):
    """T11: a verified Ed25519 signature by one party over one document version."""

    __tablename__ = "signatures"
    __table_args__ = (UniqueConstraint("document_id", "party_id"),)

    id: Mapped[int] = mapped_column(primary_key=True)
    document_id: Mapped[int] = mapped_column(ForeignKey("documents.id", ondelete="CASCADE"))
    party_id: Mapped[int] = mapped_column(ForeignKey("parties.id", ondelete="CASCADE"))
    public_key: Mapped[str] = mapped_column(String(100))
    key_fingerprint: Mapped[str] = mapped_column(String(16))
    signature: Mapped[str] = mapped_column(String(200))
    signed_sha256: Mapped[str] = mapped_column(String(64))
    device_id: Mapped[str | None] = mapped_column(String(100))
    signed_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utcnow)

    document: Mapped[Document] = relationship(back_populates="signatures")
